## Завдання.
1. Згенерувати N тривимiрних незалежних випадкових векторiв, в яких координати незалежнi,
першi двi координати мають показниковий розподiл з параметром 1, третя координата має
стандартний нормальний розподiл.

2. Реалiзувати алгоритм Козинця пошуку роздiляючого вектора для опуклої оболонки згенеро-
ваних векторiв. Алгоритм має працювати для довiльного N.

In [6]:
import numpy as np
from scipy.optimize import golden

In [7]:
def generate_vectors(n):
    
    return np.column_stack([
        np.random.exponential(scale=1, size=(n, 1)),
        np.random.exponential(scale=1, size=(n, 1)),
        np.random.normal(scale=1, size=(n, 1))
    ])

In [8]:
def kozinets_algorithm(vectors, separating_vector):
    
    for j, vector in enumerate(vectors):
        scalar_product = np.dot(vector, separating_vector)
        
        if scalar_product <= 0:
            print(f"Знайдений вектор x^j задовольняє умову (a_t, x^j) <= 0")
            print(f"j: {j}, \nx^j: {vector}, \na_t: {separating_vector}, \nscalar_product: {scalar_product}")
            
            def objective(k):
                
                return np.linalg.norm((1 - k) * separating_vector + k * vector)

            optimal_k = golden(objective, full_output=True)[0]
            new_vector = (1 - optimal_k) * separating_vector + optimal_k * vector
            
            print("a_t1: ", new_vector, "\n")
            
            return kozinets_algorithm(vectors, new_vector)
    
    return separating_vector

In [9]:
def main():
    try:
        n = int(input("Введіть кількість векторів (n): "))
        if n <= 0:
            raise ValueError("Кількість векторів має бути більше нуля.")
    except ValueError as e:
        print(f"Помилка вводу: {e}")
        return
    
    vectors = generate_vectors(n)
    
    print("\nЗгенеровані вектори:")
    print(vectors[:10]) 
    
    initial_vector = vectors[0]
    separating_vector = kozinets_algorithm(vectors, initial_vector)
    
    print("\nРозділяючий вектор: ", separating_vector)


In [11]:
if __name__ == "__main__":
    main()

Введіть кількість векторів (n): 57

Згенеровані вектори:
[[ 0.03097315  0.02242753  1.05140369]
 [ 0.46159911  0.76678178 -0.16749676]
 [ 0.74552934  0.45280636 -1.78275042]
 [ 2.34539548  1.63850008 -0.66159801]
 [ 0.78368305  1.42595214  0.12726013]
 [ 2.0461182   0.4955633   1.04809432]
 [ 1.11901889  2.04456729  0.9516142 ]
 [ 0.20108005  0.06515971  0.8295498 ]
 [ 0.42753741  0.07397087  1.20664462]
 [ 0.09286388  0.04570456 -1.23416187]]
Знайдений вектор x^j задовольняє умову (a_t, x^j) <= 0
j: 1, 
x^j: [ 0.46159911  0.76678178 -0.16749676], 
a_t: [0.03097315 0.02242753 1.05140369], 
scalar_product: -0.14461250848048945
a_t1:  [0.27316893 0.44107266 0.36586085] 

Знайдений вектор x^j задовольняє умову (a_t, x^j) <= 0
j: 2, 
x^j: [ 0.74552934  0.45280636 -1.78275042], 
a_t: [0.27316893 0.44107266 0.36586085], 
scalar_product: -0.24886262309526286
a_t1:  [0.33679228 0.4426531  0.07645928] 

Знайдений вектор x^j задовольняє умову (a_t, x^j) <= 0
j: 9, 
x^j: [ 0.09286388  0.04570456 